import type { AnatomicalStructure, StructureNames } from "@/types/anatomy";
import courseNamesJson from "./courseNames.json";

/**
 * A structure's names as her course writes them (https://medintzfat.com/anatomy/),
 * generated by scripts/course/medintzfat/course_names.py. Keyed by the
 * side-less id (`bilateralGroupId`, or the id of a midline structure); a
 * sided id (e.g. "coronary-artery-right") carries aliases for that side only.
 */
export interface CourseName {
  en?: string;
  /** Course page the English name is taken from. */
  source?: string;
  /** How often the site uses this wording (for reviewers). */
  uses?: number;
  /** Other course wordings for the same structure — searchable, not shown. */
  aliases?: string[];
  he?: string;
  heSource?: string;
  heAliases?: string[];
}

export const COURSE_NAMES: Readonly<Record<string, CourseName>> =
  courseNamesJson;

const appended = (
  list: string[] | undefined,
  extra: (string | undefined)[],
) => {
  const all = [...(list ?? [])];
  for (const item of extra)
    if (item !== undefined && !all.includes(item)) all.push(item);
  return all;
};

/**
 * Shows the course's names: the English (and, where the course has one, the
 * Hebrew) name is replaced by the course's wording. A structure the course
 * names in English only shows no Hebrew. The replaced names and the course's
 * other wordings stay searchable as aliases. Course names are
 * still unverified: they are copied, but matched to structures by a script.
 */
export function withCourseName(
  structure: AnatomicalStructure,
  courseNames: Readonly<Record<string, CourseName>> = COURSE_NAMES,
): AnatomicalStructure {
  const shared = courseNames[structure.bilateralGroupId ?? structure.id];
  const ownSide = structure.bilateralGroupId
    ? courseNames[structure.id]
    : undefined;
  if (!shared && !ownSide) return structure;

  const names: StructureNames = { ...structure.names };
  const aliases = { ...structure.aliases };
  if (shared?.en) {
    names.en = { text: shared.en, verified: false, source: shared.source };
    if (shared.en !== structure.names.en.text)
      aliases.en = appended(aliases.en, [structure.names.en.text]);
  }
  aliases.en = appended(aliases.en, [
    ...(shared?.aliases ?? []),
    ...(ownSide?.aliases ?? []),
  ]);
  const ownHebrew = structure.names.he?.text;
  if (shared?.he) {
    names.he = { text: shared.he, verified: false, source: shared.heSource };
    aliases.he = appended(aliases.he, [
      ownHebrew === shared.he ? undefined : ownHebrew,
      ...(shared.heAliases ?? []),
    ]);
  } else if (shared?.en && ownHebrew !== undefined) {
    // The course names it in English only: show no Hebrew it doesn't use.
    delete names.he;
    aliases.he = appended(aliases.he, [ownHebrew]);
  }
  if (aliases.en.length === 0) delete aliases.en;
  return { ...structure, names, aliases };
}
